import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'app.dart';
import 'core/di/service_locator.dart';

// NOTE: Firebase is initialised here once google-services.json /
// GoogleService-Info.plist are injected via CI secrets (see spec §Security).
// For local development without Firebase config, set kFirebaseEnabled = false.
const bool kFirebaseEnabled = false;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Lock orientation to portrait-up only (TASK-VMG-001 / AC-001).
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]);

  if (kFirebaseEnabled) {
    // ignore: avoid_print
    await _initFirebase();
  }

  setupServiceLocator();

  runApp(const VeggieMergeApp());
}

Future<void> _initFirebase() async {
  // Import firebase_options.dart (generated by `flutterfire configure`).
  // Run: dart pub global activate flutterfire_cli
  //      flutterfire configure --project=<your-firebase-project-id>
  // Then set kFirebaseEnabled = true above.
  throw UnimplementedError(
    'firebase_options.dart has not been generated. '
    'Run `flutterfire configure` and set kFirebaseEnabled = true.',
  );
}